id: I88B7CB72
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:48:49.670326+00:00
last_modified: 2022-12-15 07:48:49.670331+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-066-010
  eft-text-version: 1.0.1 2021
  title: Toh_252-The_Fourfold_Accomplishment-v2
bases:
  5BB5:
    source_metadata: null
    order: 1
    base_file: 5BB5.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
